import 'package:flutter/material.dart';

class HelpScreen extends StatelessWidget {
  const HelpScreen({super.key});
  static const _faq = [
    ('Bagaimana cara mengisi presensi harian?', 'Buka menu Presensi, ambil foto selfie di lokasi yang ditentukan, lalu klik tombol Kirim Presensi saat jam masuk atau pulang.'),
    ('Kapan batas akhir pengisian logbook mingguan?', 'Lengkapi logbook setiap hari kerja dan pastikan seluruh aktivitas minggu berjalan tercatat sebelum minggu berakhir.'),
    ('Bagaimana jika saya lupa melakukan check-out?', 'Segera hubungi pembimbing atau administrator OPD untuk mendapatkan arahan terkait presensi Anda.'),
    ('Di mana saya bisa mengunduh sertifikat magang?', 'Sertifikat yang telah diterbitkan tersedia pada menu Nilai & Sertifikat.'),
  ];
  @override Widget build(BuildContext context) => Scaffold(appBar: AppBar(title: const Text('Bantuan')), body: SafeArea(child: ListView(padding: const EdgeInsets.all(20), children: [const Text('Bantuan', style: TextStyle(fontSize: 23, fontWeight: FontWeight.w800)), const SizedBox(height: 6), const Text('Hubungi kami jika ada pertanyaan atau masalah.'), const SizedBox(height: 22), Card(shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)), child: const ListTile(leading: CircleAvatar(backgroundColor: Color(0xFFFFF1CC), child: Icon(Icons.article_outlined, color: Color(0xFF986B13))), title: Text('FAQ', style: TextStyle(fontWeight: FontWeight.w700)), subtitle: Text('Pertanyaan yang sering diajukan'), trailing: Icon(Icons.chevron_right))), const SizedBox(height: 24), const Text('Pertanyaan Populer', style: TextStyle(fontSize: 16, fontWeight: FontWeight.w700)), const SizedBox(height: 10), ..._faq.map((item) => Card(shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)), child: ExpansionTile(title: Text(item.$1, style: const TextStyle(fontSize: 14, fontWeight: FontWeight.w700)), childrenPadding: const EdgeInsets.fromLTRB(16, 0, 16, 16), children: [Text(item.$2, style: const TextStyle(height: 1.45, color: Color(0xFF4B5565)))]))), const SizedBox(height: 28), const Text('"Kami siap membantu Anda menyukseskan\nprogram magang Anda."', textAlign: TextAlign.center, style: TextStyle(color: Color(0xFF4B5565))), const SizedBox(height: 36), const Divider(), const SizedBox(height: 10), const Text('Panduan Magang', textAlign: TextAlign.center, style: TextStyle(fontWeight: FontWeight.w700, color: Color(0xFF2563EB))), const SizedBox(height: 6), const Text('© 2026 Ruwa Magang. All Rights Reserved.', textAlign: TextAlign.center, style: TextStyle(fontSize: 11, color: Color(0xFF6B7280)))])));
}
